version: "3"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 9000:9000
    restart: always